//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadoService.DAl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> phone { get; set; }
        public string defect { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> deadLine { get; set; }
    }
}
